"""add company tax offences

Revision ID: 15af5a5b1b7d
Revises: 52053a5fb63b
Create Date: 2026-09-14 00:18:15.946228

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15af5a5b1b7d'
down_revision: Union[str, Sequence[str], None] = '52053a5fb63b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_tax_offences',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('company_id', sa.BigInteger(), nullable=False),
    sa.Column('dataset_id', sa.BigInteger(), nullable=False),
    sa.Column('data_date', sa.Date(), nullable=False),
    sa.Column('document_date', sa.Date(), nullable=True),
    sa.Column('source_document_id', sa.String(length=100), nullable=False),
    sa.Column('fine_amount', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['dataset_id'], ['data_sets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dataset_id', 'source_document_id', name='uq_company_tax_offence_dataset_document')
    )
    op.create_index(op.f('ix_company_tax_offences_company_id'), 'company_tax_offences', ['company_id'], unique=False)
    op.create_index(op.f('ix_company_tax_offences_data_date'), 'company_tax_offences', ['data_date'], unique=False)
    op.create_index(op.f('ix_company_tax_offences_dataset_id'), 'company_tax_offences', ['dataset_id'], unique=False)
    op.create_index(op.f('ix_company_tax_offences_fine_amount'), 'company_tax_offences', ['fine_amount'], unique=False)
    op.create_index(op.f('ix_company_tax_offences_source_document_id'), 'company_tax_offences', ['source_document_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_company_tax_offences_source_document_id'), table_name='company_tax_offences')
    op.drop_index(op.f('ix_company_tax_offences_fine_amount'), table_name='company_tax_offences')
    op.drop_index(op.f('ix_company_tax_offences_dataset_id'), table_name='company_tax_offences')
    op.drop_index(op.f('ix_company_tax_offences_data_date'), table_name='company_tax_offences')
    op.drop_index(op.f('ix_company_tax_offences_company_id'), table_name='company_tax_offences')
    op.drop_table('company_tax_offences')
    # ### end Alembic commands ###
