"""add company tax debt history

Revision ID: 52053a5fb63b
Revises: e82b1a901d05
Create Date: 2026-09-13 23:54:01.598445

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52053a5fb63b'
down_revision: Union[str, Sequence[str], None] = 'e82b1a901d05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_tax_debt_snapshots',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('company_id', sa.BigInteger(), nullable=False),
    sa.Column('dataset_id', sa.BigInteger(), nullable=False),
    sa.Column('data_date', sa.Date(), nullable=False),
    sa.Column('document_date', sa.Date(), nullable=True),
    sa.Column('source_document_id', sa.String(length=100), nullable=True),
    sa.Column('total_arrears', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('total_penalties', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('total_fines', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('total_debt', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('item_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['dataset_id'], ['data_sets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'dataset_id', 'data_date', name='uq_company_tax_debt_company_dataset_date')
    )
    op.create_index(op.f('ix_company_tax_debt_snapshots_company_id'), 'company_tax_debt_snapshots', ['company_id'], unique=False)
    op.create_index(op.f('ix_company_tax_debt_snapshots_data_date'), 'company_tax_debt_snapshots', ['data_date'], unique=False)
    op.create_index(op.f('ix_company_tax_debt_snapshots_dataset_id'), 'company_tax_debt_snapshots', ['dataset_id'], unique=False)
    op.create_index(op.f('ix_company_tax_debt_snapshots_source_document_id'), 'company_tax_debt_snapshots', ['source_document_id'], unique=False)
    op.create_index(op.f('ix_company_tax_debt_snapshots_total_debt'), 'company_tax_debt_snapshots', ['total_debt'], unique=False)
    op.create_table('company_tax_debt_items',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('snapshot_id', sa.BigInteger(), nullable=False),
    sa.Column('tax_name', sa.String(length=1000), nullable=False),
    sa.Column('arrears', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('penalties', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('fines', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['snapshot_id'], ['company_tax_debt_snapshots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('snapshot_id', 'tax_name', name='uq_company_tax_debt_snapshot_tax_name')
    )
    op.create_index(op.f('ix_company_tax_debt_items_snapshot_id'), 'company_tax_debt_items', ['snapshot_id'], unique=False)
    op.create_index(op.f('ix_company_tax_debt_items_tax_name'), 'company_tax_debt_items', ['tax_name'], unique=False)
    op.drop_index(op.f('ix_companies_inn_pattern'), table_name='companies', postgresql_ops={'inn': 'varchar_pattern_ops'})
    op.drop_index(op.f('ix_companies_name_trgm'), table_name='companies', postgresql_ops={'name': 'gin_trgm_ops'}, postgresql_using='gin')
    op.drop_index(op.f('ix_companies_ogrn_pattern'), table_name='companies', postgresql_ops={'ogrn': 'varchar_pattern_ops'})
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_companies_ogrn_pattern'), 'companies', ['ogrn'], unique=False, postgresql_ops={'ogrn': 'varchar_pattern_ops'})
    op.create_index(op.f('ix_companies_name_trgm'), 'companies', ['name'], unique=False, postgresql_ops={'name': 'gin_trgm_ops'}, postgresql_using='gin')
    op.create_index(op.f('ix_companies_inn_pattern'), 'companies', ['inn'], unique=False, postgresql_ops={'inn': 'varchar_pattern_ops'})
    op.drop_index(op.f('ix_company_tax_debt_items_tax_name'), table_name='company_tax_debt_items')
    op.drop_index(op.f('ix_company_tax_debt_items_snapshot_id'), table_name='company_tax_debt_items')
    op.drop_table('company_tax_debt_items')
    op.drop_index(op.f('ix_company_tax_debt_snapshots_total_debt'), table_name='company_tax_debt_snapshots')
    op.drop_index(op.f('ix_company_tax_debt_snapshots_source_document_id'), table_name='company_tax_debt_snapshots')
    op.drop_index(op.f('ix_company_tax_debt_snapshots_dataset_id'), table_name='company_tax_debt_snapshots')
    op.drop_index(op.f('ix_company_tax_debt_snapshots_data_date'), table_name='company_tax_debt_snapshots')
    op.drop_index(op.f('ix_company_tax_debt_snapshots_company_id'), table_name='company_tax_debt_snapshots')
    op.drop_table('company_tax_debt_snapshots')
    # ### end Alembic commands ###
