"""add source registry

Revision ID: 5a82bf2241c3
Revises: f5b35de56e2a
Create Date: 2026-09-13 16:50:58.018749

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5a82bf2241c3'
down_revision: Union[str, Sequence[str], None] = 'f5b35de56e2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_sources',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('website_url', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_sources_code'), 'data_sources', ['code'], unique=True)
    op.create_index(op.f('ix_data_sources_enabled'), 'data_sources', ['enabled'], unique=False)
    op.create_index(op.f('ix_data_sources_priority'), 'data_sources', ['priority'], unique=False)
    op.create_index(op.f('ix_data_sources_source_type'), 'data_sources', ['source_type'], unique=False)
    op.create_table('company_source_data',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('company_id', sa.BigInteger(), nullable=False),
    sa.Column('source_id', sa.BigInteger(), nullable=False),
    sa.Column('normalized_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('source_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['data_sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'source_id', name='uq_company_source_data')
    )
    op.create_index(op.f('ix_company_source_data_company_id'), 'company_source_data', ['company_id'], unique=False)
    op.create_index(op.f('ix_company_source_data_source_id'), 'company_source_data', ['source_id'], unique=False)
    op.create_index(op.f('ix_company_source_data_status'), 'company_source_data', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_company_source_data_status'), table_name='company_source_data')
    op.drop_index(op.f('ix_company_source_data_source_id'), table_name='company_source_data')
    op.drop_index(op.f('ix_company_source_data_company_id'), table_name='company_source_data')
    op.drop_table('company_source_data')
    op.drop_index(op.f('ix_data_sources_source_type'), table_name='data_sources')
    op.drop_index(op.f('ix_data_sources_priority'), table_name='data_sources')
    op.drop_index(op.f('ix_data_sources_enabled'), table_name='data_sources')
    op.drop_index(op.f('ix_data_sources_code'), table_name='data_sources')
    op.drop_table('data_sources')
    # ### end Alembic commands ###
