"""add company tax payments

Revision ID: 627b6a78b250
Revises: 15af5a5b1b7d
Create Date: 2026-09-14 09:44:48.698922

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '627b6a78b250'
down_revision: Union[str, Sequence[str], None] = '15af5a5b1b7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_tax_payment_snapshots',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('company_id', sa.BigInteger(), nullable=False),
    sa.Column('dataset_id', sa.BigInteger(), nullable=False),
    sa.Column('data_date', sa.Date(), nullable=False),
    sa.Column('data_year', sa.Integer(), nullable=False),
    sa.Column('document_date', sa.Date(), nullable=True),
    sa.Column('source_document_id', sa.String(length=100), nullable=False),
    sa.Column('source_company_name', sa.String(length=1000), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=22, scale=2), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=22, scale=2), nullable=False),
    sa.Column('insurance_amount', sa.Numeric(precision=22, scale=2), nullable=False),
    sa.Column('penalty_amount', sa.Numeric(precision=22, scale=2), nullable=False),
    sa.Column('non_tax_amount', sa.Numeric(precision=22, scale=2), nullable=False),
    sa.Column('other_amount', sa.Numeric(precision=22, scale=2), nullable=False),
    sa.Column('source_item_count', sa.Integer(), nullable=False),
    sa.Column('stored_item_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['dataset_id'], ['data_sets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'dataset_id', 'data_date', name='uq_company_tax_payment_company_dataset_date'),
    sa.UniqueConstraint('dataset_id', 'source_document_id', name='uq_company_tax_payment_dataset_document')
    )
    op.create_index(op.f('ix_company_tax_payment_snapshots_company_id'), 'company_tax_payment_snapshots', ['company_id'], unique=False)
    op.create_index(op.f('ix_company_tax_payment_snapshots_data_date'), 'company_tax_payment_snapshots', ['data_date'], unique=False)
    op.create_index(op.f('ix_company_tax_payment_snapshots_data_year'), 'company_tax_payment_snapshots', ['data_year'], unique=False)
    op.create_index(op.f('ix_company_tax_payment_snapshots_dataset_id'), 'company_tax_payment_snapshots', ['dataset_id'], unique=False)
    op.create_index(op.f('ix_company_tax_payment_snapshots_source_document_id'), 'company_tax_payment_snapshots', ['source_document_id'], unique=False)
    op.create_index(op.f('ix_company_tax_payment_snapshots_total_amount'), 'company_tax_payment_snapshots', ['total_amount'], unique=False)
    op.create_table('company_tax_payment_items',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('snapshot_id', sa.BigInteger(), nullable=False),
    sa.Column('tax_name', sa.String(length=1000), nullable=False),
    sa.Column('payment_type', sa.String(length=30), nullable=False),
    sa.Column('amount', sa.Numeric(precision=22, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['snapshot_id'], ['company_tax_payment_snapshots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('snapshot_id', 'tax_name', name='uq_company_tax_payment_snapshot_tax_name')
    )
    op.create_index(op.f('ix_company_tax_payment_items_amount'), 'company_tax_payment_items', ['amount'], unique=False)
    op.create_index(op.f('ix_company_tax_payment_items_payment_type'), 'company_tax_payment_items', ['payment_type'], unique=False)
    op.create_index(op.f('ix_company_tax_payment_items_snapshot_id'), 'company_tax_payment_items', ['snapshot_id'], unique=False)
    op.create_index(op.f('ix_company_tax_payment_items_tax_name'), 'company_tax_payment_items', ['tax_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_company_tax_payment_items_tax_name'), table_name='company_tax_payment_items')
    op.drop_index(op.f('ix_company_tax_payment_items_snapshot_id'), table_name='company_tax_payment_items')
    op.drop_index(op.f('ix_company_tax_payment_items_payment_type'), table_name='company_tax_payment_items')
    op.drop_index(op.f('ix_company_tax_payment_items_amount'), table_name='company_tax_payment_items')
    op.drop_table('company_tax_payment_items')
    op.drop_index(op.f('ix_company_tax_payment_snapshots_total_amount'), table_name='company_tax_payment_snapshots')
    op.drop_index(op.f('ix_company_tax_payment_snapshots_source_document_id'), table_name='company_tax_payment_snapshots')
    op.drop_index(op.f('ix_company_tax_payment_snapshots_dataset_id'), table_name='company_tax_payment_snapshots')
    op.drop_index(op.f('ix_company_tax_payment_snapshots_data_year'), table_name='company_tax_payment_snapshots')
    op.drop_index(op.f('ix_company_tax_payment_snapshots_data_date'), table_name='company_tax_payment_snapshots')
    op.drop_index(op.f('ix_company_tax_payment_snapshots_company_id'), table_name='company_tax_payment_snapshots')
    op.drop_table('company_tax_payment_snapshots')
    # ### end Alembic commands ###
