"""add master registry fields

Revision ID: 77f5d386f48d
Revises: cc7fe6101d88
Create Date: 2026-09-13 21:50:24.438579

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77f5d386f48d'
down_revision: Union[str, Sequence[str], None] = 'cc7fe6101d88'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('entity_type', sa.String(length=30), nullable=True))
    op.add_column('companies', sa.Column('registration_date', sa.Date(), nullable=True))
    op.add_column('companies', sa.Column('termination_date', sa.Date(), nullable=True))
    op.add_column('companies', sa.Column('region_code', sa.String(length=3), nullable=True))
    op.add_column('companies', sa.Column('master_dataset_id', sa.BigInteger(), nullable=True))
    op.add_column('companies', sa.Column('master_data_date', sa.Date(), nullable=True))
    op.create_index(op.f('ix_companies_entity_type'), 'companies', ['entity_type'], unique=False)
    op.create_index(op.f('ix_companies_master_data_date'), 'companies', ['master_data_date'], unique=False)
    op.create_index(op.f('ix_companies_master_dataset_id'), 'companies', ['master_dataset_id'], unique=False)
    op.create_index(op.f('ix_companies_region_code'), 'companies', ['region_code'], unique=False)
    op.create_index(op.f('ix_companies_registration_date'), 'companies', ['registration_date'], unique=False)
    op.create_index(op.f('ix_companies_termination_date'), 'companies', ['termination_date'], unique=False)
    op.create_foreign_key(None, 'companies', 'data_sets', ['master_dataset_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'companies', type_='foreignkey')
    op.drop_index(op.f('ix_companies_termination_date'), table_name='companies')
    op.drop_index(op.f('ix_companies_registration_date'), table_name='companies')
    op.drop_index(op.f('ix_companies_region_code'), table_name='companies')
    op.drop_index(op.f('ix_companies_master_dataset_id'), table_name='companies')
    op.drop_index(op.f('ix_companies_master_data_date'), table_name='companies')
    op.drop_index(op.f('ix_companies_entity_type'), table_name='companies')
    op.drop_column('companies', 'master_data_date')
    op.drop_column('companies', 'master_dataset_id')
    op.drop_column('companies', 'region_code')
    op.drop_column('companies', 'termination_date')
    op.drop_column('companies', 'registration_date')
    op.drop_column('companies', 'entity_type')
    # ### end Alembic commands ###
