"""add company headcounts

Revision ID: cc7fe6101d88
Revises: 3c616a1ff3c4
Create Date: 2026-09-13 20:48:15.863890

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc7fe6101d88'
down_revision: Union[str, Sequence[str], None] = '3c616a1ff3c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_headcounts',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('company_id', sa.BigInteger(), nullable=False),
    sa.Column('dataset_id', sa.BigInteger(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('employee_count', sa.Integer(), nullable=False),
    sa.Column('source_document_id', sa.String(length=100), nullable=True),
    sa.Column('source_document_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['dataset_id'], ['data_sets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'year', 'dataset_id', name='uq_company_headcounts_company_year_dataset')
    )
    op.create_index(op.f('ix_company_headcounts_company_id'), 'company_headcounts', ['company_id'], unique=False)
    op.create_index(op.f('ix_company_headcounts_dataset_id'), 'company_headcounts', ['dataset_id'], unique=False)
    op.create_index(op.f('ix_company_headcounts_year'), 'company_headcounts', ['year'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_company_headcounts_year'), table_name='company_headcounts')
    op.drop_index(op.f('ix_company_headcounts_dataset_id'), table_name='company_headcounts')
    op.drop_index(op.f('ix_company_headcounts_company_id'), table_name='company_headcounts')
    op.drop_table('company_headcounts')
    # ### end Alembic commands ###
