"""add company msp profiles

Revision ID: e82b1a901d05
Revises: 77f5d386f48d
Create Date: 2026-09-13 22:05:53.611211

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e82b1a901d05'
down_revision: Union[str, Sequence[str], None] = '77f5d386f48d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_msp_profiles',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('company_id', sa.BigInteger(), nullable=False),
    sa.Column('dataset_id', sa.BigInteger(), nullable=False),
    sa.Column('data_date', sa.Date(), nullable=False),
    sa.Column('inclusion_date', sa.Date(), nullable=True),
    sa.Column('subject_type_code', sa.String(length=10), nullable=True),
    sa.Column('category_code', sa.String(length=10), nullable=True),
    sa.Column('is_new_code', sa.String(length=10), nullable=True),
    sa.Column('social_enterprise_code', sa.String(length=10), nullable=True),
    sa.Column('employee_count', sa.Integer(), nullable=True),
    sa.Column('source_document_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['dataset_id'], ['data_sets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'dataset_id', name='uq_company_msp_profile_company_dataset')
    )
    op.create_index(op.f('ix_company_msp_profiles_category_code'), 'company_msp_profiles', ['category_code'], unique=False)
    op.create_index(op.f('ix_company_msp_profiles_company_id'), 'company_msp_profiles', ['company_id'], unique=False)
    op.create_index(op.f('ix_company_msp_profiles_data_date'), 'company_msp_profiles', ['data_date'], unique=False)
    op.create_index(op.f('ix_company_msp_profiles_dataset_id'), 'company_msp_profiles', ['dataset_id'], unique=False)
    op.create_index(op.f('ix_company_msp_profiles_subject_type_code'), 'company_msp_profiles', ['subject_type_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_company_msp_profiles_subject_type_code'), table_name='company_msp_profiles')
    op.drop_index(op.f('ix_company_msp_profiles_dataset_id'), table_name='company_msp_profiles')
    op.drop_index(op.f('ix_company_msp_profiles_data_date'), table_name='company_msp_profiles')
    op.drop_index(op.f('ix_company_msp_profiles_company_id'), table_name='company_msp_profiles')
    op.drop_index(op.f('ix_company_msp_profiles_category_code'), table_name='company_msp_profiles')
    op.drop_table('company_msp_profiles')
    # ### end Alembic commands ###
