"""create company base tables

Revision ID: f2ffa240001f
Revises: 
Create Date: 2026-09-13 15:56:58.561527

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2ffa240001f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('inn', sa.String(length=12), nullable=False),
    sa.Column('kpp', sa.String(length=9), nullable=True),
    sa.Column('ogrn', sa.String(length=15), nullable=True),
    sa.Column('okpo', sa.String(length=12), nullable=True),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('short_name', sa.String(length=500), nullable=True),
    sa.Column('full_name', sa.Text(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('activity', sa.Text(), nullable=True),
    sa.Column('okved', sa.String(length=20), nullable=True),
    sa.Column('website', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('source_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_companies_inn'), 'companies', ['inn'], unique=True)
    op.create_index(op.f('ix_companies_kpp'), 'companies', ['kpp'], unique=False)
    op.create_index(op.f('ix_companies_name'), 'companies', ['name'], unique=False)
    op.create_index(op.f('ix_companies_ogrn'), 'companies', ['ogrn'], unique=True)
    op.create_index(op.f('ix_companies_okpo'), 'companies', ['okpo'], unique=False)
    op.create_index(op.f('ix_companies_okved'), 'companies', ['okved'], unique=False)
    op.create_index(op.f('ix_companies_status'), 'companies', ['status'], unique=False)
    op.create_table('company_contacts',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('company_id', sa.BigInteger(), nullable=False),
    sa.Column('contact_type', sa.String(length=30), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'contact_type', 'value', name='uq_company_contact')
    )
    op.create_index(op.f('ix_company_contacts_company_id'), 'company_contacts', ['company_id'], unique=False)
    op.create_index(op.f('ix_company_contacts_contact_type'), 'company_contacts', ['contact_type'], unique=False)
    op.create_table('company_financials',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('company_id', sa.BigInteger(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('revenue', sa.BigInteger(), nullable=True),
    sa.Column('company_value', sa.BigInteger(), nullable=True),
    sa.Column('employee_count', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_financials_company_id'), 'company_financials', ['company_id'], unique=False)
    op.create_index(op.f('ix_company_financials_year'), 'company_financials', ['year'], unique=False)
    op.create_table('company_identifiers',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('company_id', sa.BigInteger(), nullable=False),
    sa.Column('identifier_type', sa.String(length=50), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'identifier_type', 'value', name='uq_company_identifier')
    )
    op.create_index(op.f('ix_company_identifiers_company_id'), 'company_identifiers', ['company_id'], unique=False)
    op.create_index(op.f('ix_company_identifiers_identifier_type'), 'company_identifiers', ['identifier_type'], unique=False)
    op.create_table('company_managers',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('company_id', sa.BigInteger(), nullable=False),
    sa.Column('last_name', sa.String(length=200), nullable=True),
    sa.Column('first_name', sa.String(length=200), nullable=True),
    sa.Column('middle_name', sa.String(length=200), nullable=True),
    sa.Column('full_name', sa.String(length=600), nullable=True),
    sa.Column('position', sa.String(length=300), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_managers_company_id'), 'company_managers', ['company_id'], unique=False)
    op.create_index(op.f('ix_company_managers_full_name'), 'company_managers', ['full_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_company_managers_full_name'), table_name='company_managers')
    op.drop_index(op.f('ix_company_managers_company_id'), table_name='company_managers')
    op.drop_table('company_managers')
    op.drop_index(op.f('ix_company_identifiers_identifier_type'), table_name='company_identifiers')
    op.drop_index(op.f('ix_company_identifiers_company_id'), table_name='company_identifiers')
    op.drop_table('company_identifiers')
    op.drop_index(op.f('ix_company_financials_year'), table_name='company_financials')
    op.drop_index(op.f('ix_company_financials_company_id'), table_name='company_financials')
    op.drop_table('company_financials')
    op.drop_index(op.f('ix_company_contacts_contact_type'), table_name='company_contacts')
    op.drop_index(op.f('ix_company_contacts_company_id'), table_name='company_contacts')
    op.drop_table('company_contacts')
    op.drop_index(op.f('ix_companies_status'), table_name='companies')
    op.drop_index(op.f('ix_companies_okved'), table_name='companies')
    op.drop_index(op.f('ix_companies_okpo'), table_name='companies')
    op.drop_index(op.f('ix_companies_ogrn'), table_name='companies')
    op.drop_index(op.f('ix_companies_name'), table_name='companies')
    op.drop_index(op.f('ix_companies_kpp'), table_name='companies')
    op.drop_index(op.f('ix_companies_inn'), table_name='companies')
    op.drop_table('companies')
    # ### end Alembic commands ###
