"""add company branches

Revision ID: f5b35de56e2a
Revises: f2ffa240001f
Create Date: 2026-09-13 16:04:37.162044

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5b35de56e2a'
down_revision: Union[str, Sequence[str], None] = 'f2ffa240001f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_branches',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('company_id', sa.BigInteger(), nullable=False),
    sa.Column('branch_code', sa.String(length=100), nullable=True),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('kpp', sa.String(length=9), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'branch_code', 'address', name='uq_company_branch')
    )
    op.create_index(op.f('ix_company_branches_branch_code'), 'company_branches', ['branch_code'], unique=False)
    op.create_index(op.f('ix_company_branches_company_id'), 'company_branches', ['company_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_company_branches_company_id'), table_name='company_branches')
    op.drop_index(op.f('ix_company_branches_branch_code'), table_name='company_branches')
    op.drop_table('company_branches')
    # ### end Alembic commands ###
